### ISSUE TITLE
Sounds like there's only upside to this package and it should be added to Meteor core?

### ISSUE THREAD

**Issue by elie222** [lamhieu-vk/hypersubs#1]
Sounds like there's only upside to this package and it should be added to Meteor core? Is there any downside to the package?

**Comment by lh0x00** [comment]
@elie222 it should not be added to Meteor core because any subscriptions after call `Meteor.subscribe` will create a new handle and it works independently. you should not use it when each connection works differently, and inside it calls `this.stop()`. it works well on other cases!

**Comment by lh0x00** [comment]
@elie222 I will close issue, if you have any questions please re-open or open issue!
thank you!
