### ISSUE TITLE
Hard crash on undefined parameter of subscription

### ISSUE THREAD

**Issue by mariusrak** [lamhieu-vk/hypersubs#2]
When some parameter of subscription is `undefined`, TypeError is thrown and app fails.
Error is from
`utils.js`:16 
```js
const listCallbacks = [lastParam.onReady, lastParam.onError, lastParam.onStop]
```
which is called by `hypersubs.js`: 189
```js
const data = argsParser.apply(self, arguments)
```

**Comment by lh0x00** [comment]
thanks @sviande to resolve the issue, I merged and published the new version.
https://atmospherejs.com/lamhieu/hypersubs
